version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/rails
permissions:
  - object: /usr/local/rails
    owner: centos
    group: centos
  AfterInstall:
    - location: codedeploy/AfterInstall.sh
      runas: centos
  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
      runas: root

